name: domain
description: domain folder

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  json_serializable: ^6.7.1
  freezed: ^2.3.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0